Make code make more sense and make it easier to read (and make it work)

diff --git a/cam_cleanup b/cam_cleanup
--- a/cam_cleanup
+++ b/cam_cleanup
@@ -1,18 +1,18 @@
 #!/bin/sh
 
-days_keep=10
-days_prune=21
+days_delete=180  # six months
+days_clean=120   # four months
 basedir=/share/media/Cameras
 
 usage() {
-  echo "usage: ${0##*/} [-h|-d|-t|-v] [-m] [ -P prune_days ] [-D days_keep] [-l location ]"
+  echo "usage: ${0##*/} [-h|-d|-t|-v] [-m] [-D DAYS_DELETE] [-C DAYS_CLEAN] [-l location]"
   echo "	-h		: This help text"
   echo "	-d		: Print debugging information"
   echo "	-t		: Print files to be deleted; do not delete"
   echo "	-v		: Print variables and exit"
   echo "	-m		: Move instead of delete (move to $basedir/deleted)"
-  echo "	-D days		: # days to keep all videos (default: $days_keep)"
-  echo "	-P days		: # days to keep activity videos (default: $days_prune; 0: don't prune)"
+  echo "	-D DAYS_DELETE	: Remove ALL videos older than DAYS_DELETE (default: $days_delete)"
+  echo "	-C DAYS_CLEAN	: Remove non-activity videos older than DAYS_CLEAN (default: $days_clean; 0: don't clean)"
   echo "	-l location	: Camera location (default: $basedir)"
   exit 1
 }
@@ -22,7 +22,7 @@ dotest=0
 move=0
 verbose=0
 
-while getopts ":hdtvmD:P:l:" opt; do
+while getopts ":hdtvmD:C:l:" opt; do
   case $opt in
     d)
       debug=1
@@ -34,10 +34,12 @@ while getopts ":hdtvmD:P:l:" opt; do
       move=1
       ;;
     D)
-      days_keep=$OPTARG
+      printf "$OPTARG" | grep -Eq "^[0-9]+$" || { echo "Error: Value for DAYS_DELETE must be an integer"; exit 1; }
+      days_delete=$OPTARG
       ;;
-    P)
-      days_prune=$OPTARG
+    C)
+      printf "$OPTARG" | grep -Eq "^[0-9]+$" || { echo "Error: Value for DAYS_CLEAN must be an integer"; exit 1; }
+      days_clean=$OPTARG
       ;;
     l)
       basedir=$OPTARG
@@ -51,18 +53,38 @@ while getopts ":hdtvmD:P:l:" opt; do
 done
 shift $((OPTIND -1))
 
+if [ $days_delete -lt $days_clean ]; then
+  echo "Warning: No directories will be cleaned because DAYS_DELETE is less than DAYS_CLEAN"
+  sleep 5
+fi
+
+if [ $debug = 1 -o $verbose = 1 ]; then
+  [ $debug = 1 ] && printf "DEBUG: "
+  echo "dotest='$dotest'"
+  [ $debug = 1 ] && printf "DEBUG: "
+  echo "move='$move'"
+  [ $debug = 1 ] && printf "DEBUG: "
+  echo "days_delete='$days_delete'"
+  [ $debug = 1 ] && printf "DEBUG: "
+  echo "days_clean='$days_clean'"
+  [ $debug = 1 ] && printf "DEBUG: "
+  echo "basedir='$basedir'"
+  [ $verbose = 1 ] && exit
+fi
+
 for cam in $basedir/*cam; do
   [ ! -d $cam ] && continue
   [ $debug = 1 ] && echo "DEBUG: Processing $cam"
 
-  if [ $days_prune != 0 ]; then
-    stop=0
-    day=$days_prune
-    while [ $stop = 0 ]; do
+    # Starting at DAYS_DELETE, delete the directory, increment and delete the next older
+    # Until a directory doesn't exist with that date string
+    stophere=0
+    day=$days_delete
+    while [ $stophere = 0 ]; do
       deletepoint=$(date -d "$day days ago" "+%Y%m%d")
-      [ $debug = 1 ] && echo "DEBUG: Processing $cam/$deletepoint for Pruning"
+      [ -d $cam/$deletepoint ] && [ $debug = 1 ] && echo "DEBUG: Deleting $cam/$deletepoint"
       if [ ! -d $cam/$deletepoint ]; then
-        stop=1
+        stophere=1
       else
         if [ $move = 1 ]; then
           destdir=$basedir/deleted/$(basename $cam)
@@ -74,55 +96,64 @@ for cam in $basedir/*cam; do
           [ $dotest = 0 ] && rm -Rf $cam/$deletepoint
         fi
       fi
-      day=$((day + 1))
+      day=$((day + 1))  # One day older
+    done
+
+  # Starting at DAYS_CLEAN, delete all "P" files (no activity) unless they preceed or
+  # follow an "A" file (activity)
+  if [ $days_clean != 0 ]; then
+    stophere=0
+    day=$days_clean
+    while [ $stophere = 0 ]; do
+      # Reset loop variables
+      skipnext=0
+      unset previous
+      unset delete_list
+      deletepoint=$(date -d "$day days ago" "+%Y%m%d")
+      [ -d $cam/$deletepoint ] && [ $debug = 1 ] && echo "DEBUG: Cleaning $cam/$deletepoint"
+      if [ ! -d $cam/$deletepoint ]; then
+        stophere=1
+      else
+        [ $debug = 1 ] && echo "DEBUG: Processing $cam/$deletepoint/*.mp4"
+
+        for file in $(/bin/ls -1 $cam/$deletepoint/*.mp4 | sort -n 2> /dev/null); do
+          # If "A" file, remove previous from delete_list and skip the next file
+          if echo "$file" | grep -q "_A\.mp4$"; then
+            [ $debug = 1 ] && echo "DEBUG: Not adding $file to delete_list"
+            if [ -n "$previous" ]; then
+              old_dl="$delete_list"
+              delete_list=$(echo "$delete_list" | sed "s^ $previous^^")
+              [ "$old_dl" != "$delete_list" ] && [ $debug = 1 ] && echo "DEBUG: Removing $previous from delete_list"
+            fi
+            skipnext=1
+          # If previous file was an "A" file, skip (but reset skipnext)
+          elif [ $skipnext = 1 ]; then
+            [ $debug = 1 ] && echo "DEBUG: Not adding $file to delete_list"
+            skipnext=0
+          # Add "P" file to delete_list
+          else
+            [ $debug = 1 ] && echo "DEBUG: Adding $file to delete_list"
+            delete_list="$delete_list $file"
+          fi
+          previous=$file
+        done
+
+        [ -n "$delete_list" ] && [ $debug = 1 ] && echo "DEBUG: Cleaning files: $delete_list"
+        if [ $move = 1 ]; then
+          destdir=$basedir/deleted/$(basename $cam)/$deletepoint
+          [ $debug = 1 ] && echo "DEBUG: Moving files to $destdir"
+          if [ $dotest = 0 ]; then
+            mkdir -p $destdir
+            mv $delete_list $destdir
+          fi
+        else
+          [ $debug = 1 ] && echo "DEBUG: Deleting files"
+          [ $dotest = 0 ] && rm $delete_list
+        fi
+
+        day=$((day + 1))
+      fi
     done
   fi
-
-  stop=0
-  day=$days_keep
-  unset keep_list
-  while [ $stop = 0 ]; do
-    deletepoint=$(date -d "$day days ago" "+%Y%m%d")
-    [ $debug = 1 ] && echo "DEBUG: Processing $cam/$deletepoint"
-    if [ ! -d $cam/$deletepoint ]; then
-      stop=1
-    else
-      [ $debug = 1 ] && echo "DEBUG: Processing $cam/$deletepoint/*.mp4"
-
-      for file in $(/bin/ls -1 $cam/$deletepoint/*.mp4 2> /dev/null); do
-        if [ $(echo $file | rev | cut -b 1-6) = "4pm.A_" ]; then
-          if [ -n "$previous" ] && [ $(echo $previous | rev | cut -b 1-6) != "4pm.A_" ]; then
-            [ $debug = 1 ] && echo "DEBUG: Keeping $previous"
-            keep_list="$keep_list $previous"
-          fi
-          [ $debug = 1 ] && echo "DEBUG: Keeping $file"
-          keep_list="$keep_list $file"
-        else
-          if [ -n "$previous" ] && [ $(echo $previous | rev | cut -b 1-6) = "4pm.A_" ]; then
-            [ $debug = 1 ] && echo "DEBUG: Keeping $file"
-            keep_list="$keep_list $file"
-          fi
-        fi
-        previous=$file
-      done
-      for file in $(/bin/ls -1 $cam/$deletepoint/*.mp4 2> /dev/null); do
-        if echo " $keep_list " | grep -qEv " $file "; then
-          if [ $move = 1 ]; then
-            destdir=$basedir/deleted/$(basename $cam)/$deletepoint
-            [ $debug = 1 ] && echo "DEBUG: Moving $file to $destdir"
-            if [ $dotest = 0 ]; then
-              mkdir -p $destdir
-              mv $file $destdir
-            fi
-          else
-            [ $debug = 1 ] && echo "DEBUG: Deleting $file"
-            [ $dotest = 0 ] && rm $file
-          fi
-        fi
-      done
-
-      day=$((day + 1))
-    fi
-  done
 done
 
